spring.application.name=Ecommerce-Application


spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerceDB
spring.datasource.username=omnist
spring.datasource.password=root

# Hibernate timezone
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=Asia/Kolkata


# Optional: explicitly set Hibernate dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Actuator Endpoints
#management.endpoints.web.exposure.include=*