spring.application.name=Ecommerce-Application

# Database Configuration


## Enable H2 Console
## localhost URL: http://localhost:8080/h2-console
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

# PostgresSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db?createDatabaseIfNotExist=true
spring.datasource.username=omnist
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator Endpoints
#management.endpoints.web.exposure.include=*